"""
DataNexus Era 3 — AI Operating System
Humans declare intent. AI builds, deploys, monitors, heals everything.
No pipeline configuration. No manual scheduling. Pure intention → execution.
"""
import json, time, uuid, hashlib
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Callable
from enum import Enum

class IntentType(Enum):
    REPORT      = "report"        # "I need daily sales reports"
    ALERT       = "alert"         # "alert me when revenue drops"
    PIPELINE    = "pipeline"      # "move data from X to Y"
    QUALITY     = "quality"       # "ensure data quality for X"
    COMPLIANCE  = "compliance"    # "make X DPDP compliant"
    INSIGHT     = "insight"       # "show me patterns in X"

@dataclass
class UserIntent:
    """What the human asked for — in plain language."""
    raw_text:   str
    language:   str               # "te" Telugu, "hi" Hindi, "en" English
    user_id:    str
    intent_type: Optional[IntentType] = None
    translated:  str = ""         # English translation
    intent_id:   str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at:  float = field(default_factory=time.time)

@dataclass
class GeneratedPipeline:
    """A complete Airflow DAG + Spark job auto-generated by the AI OS."""
    pipeline_id:    str
    intent_id:      str
    dag_code:       str           # Python Airflow DAG
    spark_job:      str           # PySpark transformation
    quality_suite:  str           # Great Expectations YAML
    schedule:       str           # cron expression
    estimated_sigma:float
    auto_heal:      bool = True
    created_at:     float = field(default_factory=time.time)

@dataclass
class HealAction:
    """An autonomous fix applied by the AI OS."""
    heal_id:     str = field(default_factory=lambda: str(uuid.uuid4()))
    pipeline_id: str = ""
    failure_type:str = ""
    diagnosis:   str = ""
    action:      str = ""
    success:     bool = False
    applied_at:  float = field(default_factory=time.time)


class LanguageTranslator:
    """
    NLP translator — Telugu/Hindi/Tamil/English → intent + SQL.
    In production: Llama 3.1 / Mistral running on-premise.
    """

    TRANSLATIONS = {
        # Telugu
        "చివరి నెలలో అమ్మకాలు": "sales last month",
        "అత్యధిక ఆదాయం":        "highest revenue",
        "డేటా నాణ్యత":           "data quality",
        "నివేదిక కావాలి":         "need report",
        # Hindi
        "पिछले महीने की बिक्री":  "sales last month",
        "सर्वोच्च राजस्व":         "highest revenue",
        "डेटा गुणवत्ता":           "data quality",
        "रिपोर्ट चाहिए":           "need report",
    }

    INTENT_PATTERNS = {
        IntentType.REPORT:     ["report", "dashboard", "show me", "నివేదిక", "रिपोर्ट"],
        IntentType.ALERT:      ["alert", "notify", "when", "if", "హెచ్చరిక", "सूचित"],
        IntentType.PIPELINE:   ["move", "transfer", "ingest", "sync", "తరలించు"],
        IntentType.QUALITY:    ["quality", "clean", "validate", "నాణ్యత", "गुणवत्ता"],
        IntentType.COMPLIANCE: ["compliant", "dpdp", "gdpr", "audit", "అనుగుణత"],
        IntentType.INSIGHT:    ["pattern", "trend", "analyse", "insight", "అంతర్దృష్టి"],
    }

    def translate(self, text: str, language: str) -> str:
        if language == "en":
            return text
        translated = text
        for native, english in self.TRANSLATIONS.items():
            translated = translated.replace(native, english)
        return translated

    def detect_intent(self, text: str) -> IntentType:
        text_lower = text.lower()
        for intent_type, patterns in self.INTENT_PATTERNS.items():
            if any(p in text_lower for p in patterns):
                return intent_type
        return IntentType.PIPELINE

    def text_to_sql(self, intent_text: str, available_tables: List[str]) -> str:
        """Convert natural language to Presto SQL."""
        text = intent_text.lower()
        table = available_tables[0] if available_tables else "datanexus_default"

        if "sales" in text and "last month" in text:
            return f"""
SELECT region, SUM(revenue) as total_revenue, COUNT(*) as orders
FROM {table}
WHERE sale_date >= DATE_TRUNC('month', CURRENT_DATE - INTERVAL '1' MONTH)
  AND sale_date <  DATE_TRUNC('month', CURRENT_DATE)
GROUP BY region
ORDER BY total_revenue DESC
LIMIT 20"""

        if "highest revenue" in text or "top" in text:
            return f"""
SELECT product_id, product_name, SUM(revenue) as revenue
FROM {table}
GROUP BY product_id, product_name
ORDER BY revenue DESC
LIMIT 10"""

        if "quality" in text or "sigma" in text:
            return f"""
SELECT pipeline_id, AVG(sigma_level) as avg_sigma,
       COUNT(*) as runs, SUM(defects) as total_defects
FROM datanexus_quality_log
GROUP BY pipeline_id
ORDER BY avg_sigma ASC"""

        return f"SELECT * FROM {table} LIMIT 100"


class AIOperatingSystem:
    """
    The AI OS of DataNexus Era 3.
    Receives human intentions, builds pipelines, monitors, heals — autonomously.
    """

    # Known failure patterns and their automatic fixes
    HEAL_PATTERNS = {
        "connection_timeout": {
            "diagnosis": "Source system connection timed out",
            "action":    "Retry with exponential backoff (3 attempts, 30s max wait)",
            "code":      "task.retry_delay=timedelta(seconds=30); task.retries=3",
        },
        "schema_mismatch": {
            "diagnosis": "Schema drift detected — new column added to source",
            "action":    "Quarantine new data; alert owner; apply schema evolution",
            "code":      "df = df.select([c for c in expected_cols if c in df.columns])",
        },
        "quality_drop": {
            "diagnosis": "Sigma level dropped below 4.5 threshold",
            "action":    "Quarantine batch; trigger root-cause analysis; rollback",
            "code":      "if sigma < 4.5: quarantine(df); alert_owner(); rollback()",
        },
        "oom_error": {
            "diagnosis": "Spark executor out of memory",
            "action":    "Reduce batch size by 50%; increase executor memory",
            "code":      "spark.conf.set('spark.executor.memory','8g'); reduce_batch()",
        },
        "source_unavailable": {
            "diagnosis": "Source system unavailable",
            "action":    "Switch to backup source; cache last known good data",
            "code":      "source = backup_source if primary_down() else primary_source",
        },
    }

    def __init__(self):
        self.translator    = LanguageTranslator()
        self.active_pipes  = {}   # pipeline_id → GeneratedPipeline
        self.heal_history  = []   # all HealActions taken
        self.intent_log    = []   # all user intents processed
        self.sigma_monitor = {}   # pipeline_id → current sigma
        print("[AI-OS] DataNexus AI Operating System online")

    def classify_intent(self, text: str) -> IntentType:
        """Compatibility helper used by tests and simple clients."""
        return self.translator.detect_intent(text)

    def extract_schedule(self, text: str) -> str:
        """Extract a simple cron schedule from natural language."""
        lowered = text.lower()
        if "6am" in lowered or "6 am" in lowered:
            return "0 6 * * *"
        if "daily" in lowered or "every day" in lowered:
            return "0 6 * * *"
        if "hourly" in lowered:
            return "0 * * * *"
        return "@continuous"

    def self_heal(self, error_type: str) -> dict:
        """Return a remediation plan for a known failure type without requiring a pipeline id."""
        pattern = self.HEAL_PATTERNS.get(error_type, self.HEAL_PATTERNS.get("connection_timeout"))
        return {"error_type": error_type, "diagnosis": pattern["diagnosis"], "action": pattern["action"], "code": pattern["code"]}

    def process_intent(self, raw_text: str, language: str,
                       user_id: str, available_tables: List[str]) -> dict:
        """
        Main entry: user says something → AI builds and deploys everything.
        """
        intent = UserIntent(
            raw_text  = raw_text,
            language  = language,
            user_id   = user_id,
        )
        intent.translated  = self.translator.translate(raw_text, language)
        intent.intent_type = self.translator.detect_intent(intent.translated)
        self.intent_log.append(intent)

        print(f"\n[AI-OS] Intent received: '{raw_text}'")
        print(f"[AI-OS] Language: {language} | Translated: '{intent.translated}'")
        print(f"[AI-OS] Intent type: {intent.intent_type.value}")

        if intent.intent_type == IntentType.REPORT:
            return self._build_report_pipeline(intent, available_tables)
        elif intent.intent_type == IntentType.ALERT:
            return self._build_alert_pipeline(intent, available_tables)
        elif intent.intent_type == IntentType.QUALITY:
            return self._build_quality_pipeline(intent, available_tables)
        elif intent.intent_type == IntentType.COMPLIANCE:
            return self._build_compliance_pipeline(intent, available_tables)
        else:
            return self._build_data_pipeline(intent, available_tables)

    def _build_report_pipeline(self, intent: UserIntent,
                                tables: List[str]) -> dict:
        sql = self.translator.text_to_sql(intent.translated, tables)
        pipeline_id = f"auto-report-{uuid.uuid4().hex[:6]}"

        dag_code = f'''"""Auto-generated by DataNexus AI OS | Intent: {intent.intent_id}"""
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from datetime import datetime, timedelta

default_args = {{"owner":"datanexus-ai","retries":3,"retry_delay":timedelta(seconds=30)}}

with DAG(
    dag_id="{pipeline_id}",
    schedule_interval="0 6 * * *",
    start_date=datetime(2025,1,1),
    default_args=default_args,
    tags=["auto-generated","report","sigma-5"],
) as dag:

    quality_check = PythonOperator(
        task_id="quality_gate",
        python_callable=lambda: check_sigma(min_sigma=4.5),
    )
    run_query = SparkSubmitOperator(
        task_id="run_report_query",
        application="/opt/datanexus/jobs/report_runner.py",
        conf={{"spark.sql.query": "{sql.strip()}"}},
    )
    log_to_fabric = PythonOperator(
        task_id="blockchain_log",
        python_callable=lambda: fabric_log("{pipeline_id}", "REPORT_RUN"),
    )
    quality_check >> run_query >> log_to_fabric
'''

        pipeline = GeneratedPipeline(
            pipeline_id    = pipeline_id,
            intent_id      = intent.intent_id,
            dag_code       = dag_code,
            spark_job      = f"spark.sql('''{sql}''').write.parquet('/datanexus/reports/')",
            quality_suite  = self._gen_quality_suite(tables[0] if tables else "default"),
            schedule       = "0 6 * * *",
            estimated_sigma= 5.2,
        )
        self.active_pipes[pipeline_id] = pipeline
        self.sigma_monitor[pipeline_id] = 5.2

        print(f"[AI-OS] Built report pipeline: {pipeline_id}")
        print(f"[AI-OS] SQL generated:\n{sql}")
        print(f"[AI-OS] Deploying Airflow DAG...")
        print(f"[AI-OS] Estimated quality: {pipeline.estimated_sigma}σ")

        return {
            "pipeline_id":   pipeline_id,
            "intent":        intent.translated,
            "sql":           sql,
            "schedule":      "Daily at 6AM",
            "sigma_target":  pipeline.estimated_sigma,
            "auto_heal":     True,
            "blockchain_log":True,
            "status":        "DEPLOYED",
        }

    def _build_alert_pipeline(self, intent: UserIntent, tables: List[str]) -> dict:
        pipeline_id = f"auto-alert-{uuid.uuid4().hex[:6]}"
        print(f"[AI-OS] Built alert pipeline: {pipeline_id}")
        return {"pipeline_id": pipeline_id, "type": "ALERT", "status": "DEPLOYED"}

    def _build_quality_pipeline(self, intent: UserIntent, tables: List[str]) -> dict:
        pipeline_id = f"auto-quality-{uuid.uuid4().hex[:6]}"
        print(f"[AI-OS] Built quality pipeline: {pipeline_id}")
        return {"pipeline_id": pipeline_id, "type": "QUALITY", "status": "DEPLOYED"}

    def _build_compliance_pipeline(self, intent: UserIntent, tables: List[str]) -> dict:
        pipeline_id = f"auto-compliance-{uuid.uuid4().hex[:6]}"
        print(f"[AI-OS] Built DPDP compliance pipeline: {pipeline_id}")
        return {"pipeline_id": pipeline_id, "type": "COMPLIANCE", "status": "DEPLOYED"}

    def _build_data_pipeline(self, intent: UserIntent, tables: List[str]) -> dict:
        pipeline_id = f"auto-pipeline-{uuid.uuid4().hex[:6]}"
        print(f"[AI-OS] Built data pipeline: {pipeline_id}")
        return {"pipeline_id": pipeline_id, "type": "PIPELINE", "status": "DEPLOYED"}

    def _gen_quality_suite(self, table: str) -> str:
        return f"""# Auto-generated Great Expectations suite
expectation_suite_name: {table}_auto_suite
expectations:
  - expectation_type: expect_column_values_to_not_be_null
    kwargs: {{column: id}}
  - expectation_type: expect_table_row_count_to_be_between
    kwargs: {{min_value: 1, max_value: 100000000}}
  - expectation_type: expect_column_values_to_be_unique
    kwargs: {{column: id}}
  - expectation_type: expect_table_columns_to_match_ordered_list
    kwargs: {{column_list: [id, created_at, updated_at]}}
"""

    def auto_heal(self, pipeline_id: str, error_type: str) -> HealAction:
        """
        Called when a pipeline fails. AI diagnoses and fixes automatically.
        Resolves 80%+ of failures without human intervention.
        """
        pattern = self.HEAL_PATTERNS.get(error_type, {
            "diagnosis": f"Unknown error: {error_type}",
            "action":    "Escalate to human operator",
            "code":      "alert_human(pipeline_id, error_type)",
        })

        heal = HealAction(
            pipeline_id  = pipeline_id,
            failure_type = error_type,
            diagnosis    = pattern["diagnosis"],
            action       = pattern["action"],
            success      = error_type in self.HEAL_PATTERNS,
        )

        if heal.success:
            print(f"[AI-OS] AUTO-HEALED: {error_type}")
            print(f"[AI-OS]   Diagnosis: {heal.diagnosis}")
            print(f"[AI-OS]   Action:    {heal.action}")
        else:
            print(f"[AI-OS] ESCALATING to human: {error_type}")

        self.heal_history.append(heal)
        return heal

    def monitor_sigma(self, pipeline_id: str, new_sigma: float):
        """Continuous sigma monitoring — triggers healing if drops."""
        old_sigma = self.sigma_monitor.get(pipeline_id, 6.0)
        self.sigma_monitor[pipeline_id] = new_sigma
        if new_sigma < 4.5:
            print(f"[AI-OS] SIGMA ALERT: {pipeline_id} dropped to {new_sigma}σ")
            self.auto_heal(pipeline_id, "quality_drop")
        elif new_sigma < old_sigma - 0.5:
            print(f"[AI-OS] SIGMA WARNING: {pipeline_id} declining {old_sigma}→{new_sigma}")

    def status_report(self) -> dict:
        healed = sum(1 for h in self.heal_history if h.success)
        return {
            "active_pipelines": len(self.active_pipes),
            "intents_processed":len(self.intent_log),
            "heals_applied":    len(self.heal_history),
            "heal_success_rate":f"{healed/max(len(self.heal_history),1)*100:.0f}%",
            "avg_sigma":        round(sum(self.sigma_monitor.values()) /
                                max(len(self.sigma_monitor),1), 2),
        }


# ── DEMO ──────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=== DataNexus Era 3 — AI Operating System Demo ===\n")
    ai_os = AIOperatingSystem()
    tables = ["sales_transactions", "customer_profiles", "inventory"]

    intents = [
        ("చివరి నెలలో అత్యధిక అమ్మకాలు ఏ ప్రాంతంలో?", "te"),
        ("पिछले तिमाही में सबसे ज़्यादा revenue किस product का था?", "hi"),
        ("Alert me when daily revenue drops below 10 lakhs", "en"),
        ("Make patient_records DPDP compliant automatically", "en"),
    ]

    for text, lang in intents:
        result = ai_os.process_intent(text, lang, "user_001", tables)
        print(f"  → Status: {result.get('status')} | ID: {result.get('pipeline_id')}\n")

    print("--- Simulating pipeline failures and auto-healing ---")
    for error in ["connection_timeout", "schema_mismatch", "unknown_error_xyz"]:
        ai_os.auto_heal("auto-report-abc123", error)
        print()

    print("--- AI OS Status ---")
    s = ai_os.status_report()
    for k, v in s.items():
        print(f"  {k}: {v}")
